### PR TITLE
Modify task and structure to new format

### PR DESCRIPTION
**Pull request by piyush-garg**
This will modify the task, structure, task names and
README according to new organization structure

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @PuneetPunamiya

**Review by vinamra28 — APPROVED** [review]
looking good to me but will wait once for @PuneetPunamiya's review :sweat_smile: 
/lgtm
/hold

**Comment by PuneetPunamiya** [comment]
@piyush-garg  The structure of the PR looks nice to me according to the reorg proposal :+1:

**Pull request merged**
