### PR TITLE
slack notifications 2

### PR DESCRIPTION
**Pull request by chmouel**
- Use virtualenv to generate file to get deps properly
- Use slack notifications from common tekton-asa-code script instead of our own

### CODE REVIEW

**Comment by chmouel** [comment]
testing to get /retest working

**Comment by chmouel** [comment]
do we get the webhook!

**Comment by chmouel** [comment]
/hold cancel

@vdemeester @vinamra28 @piyush-garg @pradeepitm12 ready for review....

**Review by vdemeester — APPROVED** [review]
/meow

**Pull request merged**
