### PR TITLE
Update apiVersion to use v1beta1

### PR DESCRIPTION
**Pull request by savitaashture**
JIRA: [SRVKP-646](https://issues.redhat.com/browse/SRVKP-646)

Update Task in catalog to use **v1beta1**

### CODE REVIEW

**Review by vdemeester — CHANGES_REQUESTED** [review]
Variables needs to be changed too:
- `inputs.params.FOO` -> `params.FOO`
- `inputs.resources` -> `resources.inputs`
- `outputs.resources` -> `resources.outputs`

Otherwise, looking good :+1:

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by vdemeester** [comment]
Should we wait for 0.11.0-rcx midstream to be published somewhere before merging ? 
I think we are always pointing to a branch from our docs but wasn't fully certain.

/cc @nikhil-thomas @pradeepitm12 @piyush-garg @siamaksade

**Comment by pradeepitm12** [comment]
> Should we wait for 0.11.0-rcx midstream to be published somewhere before merging ?
> I think we are always pointing to a branch from our docs but wasn't fully certain.
> 
> /cc @nikhil-thomas @pradeepitm12 @piyush-garg @siamaksade

IMHO it would be a good idea to wait till midstream

**Pull request merged**
