### PR TITLE
Use s2i:v0.8.0 tagged image for the released tasks

### PR DESCRIPTION
**Pull request by vdemeester**
I did tag manually for now, but we need to automate that too :angel: 

/cc @chmouel @piyush-garg @nikhil-thomas 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by chmouel** [comment]
Why is it proposed in master? Shouldnt be in a release-0.8.x branch instead?

master => nightly
0.8.0 => 0.8.0

?

**Comment by vdemeester** [comment]
@chmouel :man_facepalming: my bad ...

**Comment by vdemeester** [comment]
Updated the base :angel:

**Comment by chmouel** [comment]
Sweet thank you, let's merge this and make a PR in `openshift/release` so that branch get tested (with a dummy commit)

/lgtm
/approve
/meow

Thanks 🙇🏽‍♂️😻

**Pull request merged**
